export const GET_GAMES = "GET_GAMES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_GAMES = "ORDER_GAMES";
export const GET_GAMES_BY_NAME = "GET_GAMES_BY_NAME";